### PR TITLE
Fix print and read of vendor and product ids.

### PR DESCRIPTION
**Pull request by jlquinn**

### CODE REVIEW

**Comment by jlquinn** [comment]
@brianlheim Please take a look?  This is a minor fix, but it looks like I'm going to need other changes as well.

I am trying to find a recent version of hidapi to use and would prefer to contribute to one that is already being maintained.  If you're not maintaining this one, do you know who is?
Thanks!

**Comment by mossheim** [comment]
@jlquinn I will try to look at it soon. This fork is actively maintained but we don't get many PRs. If you can give an explanation about what the purpose of this PR is I'd really appreciate it, all I see is changes to a binary file.

**Comment by jlquinn** [comment]
@brianlheim I'll have to look and see what went wrong. The change is about 3 lines so I must have done something wrong making the pull request.

**Comment by mossheim** [comment]
@jlquinn it looks like you committed a compiled binary file by mistake, when you intended to commit changes to the source file. please either update this branch or close the PR, because I cannot review it in its current state.

**Pull request closed without merging**
